### ISSUE TITLE
Hard to install

### ISSUE THREAD

**Issue by qwding** [CitoEngine/cito_engine#68]
I am unfamiliar with python and django. When I try to install cito_engine and cito_plugin_server. I had come up with so many problems. I think it is caused by the version of python and django. Because the project have not update for years.
And now I have not install the cito_plugin_server.

So I think it is better to have a docker image for us to easy install.
I want to try this project.

**Comment by extremeunix** [comment]
hey @qwding thanks for your suggestion. I've been meaning to provide docker container support for a while now. I might as well get it going in next few days.

**Comment by kgrvamsi** [comment]
@qwding can you provide the output you are getting when you are installing the application?

**Comment by qwding** [comment]
@kgrvamsi  sorry, I forget. It is months ago.

**Comment by extremeunix** [comment]
@kgrvamsi @qwding I'm taking this up at #70.
