### ISSUE TITLE
django importerror cannot import name get_models

### ISSUE THREAD

**Issue by Nishithan** [CitoEngine/cito_engine#76]
When I am performing this step "**python manage.py migrate**" while installing cito engine, i am receiveing this error "**django importerror cannot import name get_models**"

**Comment by extremeunix** [comment]
@Nishithan which version of Python and Django are you using?

**Comment by extremeunix** [comment]
I was able to replicate the errors. While discussing with @twatchy, I think we definitely need to upgrade to Django 1.11.18 and clean up the deprecated codebase (about fucking time!)
#77 should solve this

**Comment by extremeunix** [comment]
I was able to replicate the errors. While discussing with @twatchy, I think we definitely need to upgrade to Django 1.11.18 and clean up the deprecated codebase (about fucking time!)
#77 should solve this

**Comment by twatchy** [comment]
Released new codebase with Django upgrade.
https://github.com/CitoEngine/cito_engine/tree/2.0.0
#78
